[metadata]
name = django-myapp
version = 0.1
description = An example Django app
long_description = file: README.rst
url = https://www.example.com/
author = Erik Lopez
author_email = yourname@example.com
license = BSD-3-Clause
classifiers =
environment :: Web Environment
framework :: Django
intended audience :: Developers
license :: OSI Approved :: BSD License
operating system :: OS Independent
programming language :: Python :: 3 :: Only
topic :: Internet :: WWW/HTTP :: Dynamic Content
[options]
include_package_data = true
packages = find:
python_requires = >=3.10
install_requires =
django >= 4.2