# Generated by Django 6.0.2 on 2026-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('passenger_name', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('seat_number', models.CharField(max_length=5)),
            ],
        ),
    ]
