"""add year field

Revision ID: 545c0ee5e38d
Revises: 7f6a81152cca
Create Date: 2026-03-07 12:54:54.935450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545c0ee5e38d'
down_revision: Union[str, Sequence[str], None] = '7f6a81152cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('year_of_pub', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'year_of_pub')
    # ### end Alembic commands ###
