# Generated by Django 6.0.2 on 2026-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.EmailField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subjectcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
                ('teacher', models.ManyToManyField(to='firstapp.teacher')),
            ],
        ),
    ]
