# Generated by Django 6.0.2 on 2026-03-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.BooleanField(default=True),
        ),
    ]
