# Generated by Django 6.0.2 on 2026-03-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_book_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covering',
            field=models.CharField(default='sin imagen', max_length=50),
            preserve_default=False,
        ),
    ]
